### ISSUE TITLE
Memory leaks in app

### ISSUE THREAD

**Issue by Aslanyan99n** [rundfunk47/stinsen#129]
I have memory leaks when using Stinsen. Can you suggest a solution for this? When I navigate to different screen multiple times, the app becomes unresponsive.
<img width="1680" alt="Screenshot 2023-11-22 at 09 38 57" src="https://github.com/rundfunk47/stinsen/assets/68569879/73ba1198-adf2-4874-aee5-002d4926f63d">

**Comment by JoeOCT91** [comment]
There also a memory leak when a coordinator is presented above the current coordinator

**Comment by akupich** [comment]
This issue was observed since iOS 17 and above. Any ideas how to temporary bypass these memory leaks?

**Comment by akupich** [comment]
Super critical issue, please take a look and publish version with fix for iOS 17 and tvOS 17 🙏

**Comment by ashishsj0** [comment]
Hi, Has there been any update on this? Too many memory leaks.

**Comment by Aslanyan99n** [comment]
> Hi, Has there been any update on this? Too many memory leaks.

Unfortunately no

**Comment by bigearsenal** [comment]
Hi there, how to reproduce? I didn't see the memory leak on ios 17

**Comment by akupichIntive** [comment]
Hey, according to later investigation I did - this issue was happening only on iOS 17.0.x, and was fixed on later versions.

**Comment by akupich** [comment]
Hey, according to later investigation I did - this issue was happening only on iOS 17.0.x, and was fixed on later versions.

**Comment by bigearsenal** [comment]
> Hey, according to later investigation I did - this issue was happening only on iOS 17.0.x, and was fixed on later versions.

Thank you

**Comment by ashishsj0** [comment]
Too many memory leaks happening again on iOS 18. Is anyone still facing them?
